name: Build on push master

on:

  push:

    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout kernel source

      uses: actions/checkout@v2

    - name: Checkout zipper

      uses: actions/checkout@v2

      with:

        repository: lemniskett/AnyKernel3

        path: zipper

        

    - name: sync source

      run: |

        sudo apt install git

        git clone https://github.com/likmj/android_gki_kernel_5.10_common/tree/android12-5.10-2022-05

        cd android12-5.10-2022-05

        

    - name: Android kernel build

 

      uses: lemniskett/android-kernel-actions@master

      id: build

      env:

        NAME: Dark-Ages-Últim

      with:

        arch: arm64

        compiler: clang/11

        defconfig: gki_defconfig

        image: Image.gz-dtb

    - name: Release build

      uses: appleboy/telegram-action@master

      with:

        to: ${{ secrets.CHANNEL_ID }}

        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}

        message: Kernel is built!, took ${{ steps.build.outputs.elapsed_time }} seconds.

        document: ${{ steps.build.outputs.outfile }}
