name: Build on push master

on:

  push:

    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout kernel source

      uses: actions/checkout@v2

    - name: Checkout zipper

      uses: actions/checkout@v2

      with:

        repository: lemniskett/AnyKernel3

        path: zipper
        
    - name: sync source

      run: |

        sudo apt install repo -y
        mkdir android-kernel && cd android-kernel
        repo init -u https://android.googlesource.com/kernel/manifest -b android-msm-crosshatch-4.9-android12
        repo sync
        build/build.sh
      
    - name: Release build

      uses: appleboy/telegram-action@master

      with:

        to: ${{ secrets.CHANNEL_ID }}

        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}

        message: Kernel is built!, took ${{ steps.build.outputs.elapsed_time }} seconds.

        document: ${{ steps.build.outputs.outfile }}
